name: myfpro
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
